# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

version: "2"

services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.notebook
    image: geo-notebook
    container_name: plotting
    volumes:
     - .:/home/jovyan/work
     - ./data:/data
    ports:
      - "8888:8888"